### ISSUE TITLE
ERROR: Unknown plugin "transform-runtime"

### ISSUE THREAD

**Issue by davidchl** [creativetimofficial/vue-paper-dashboard-pro#18]
Hello, we used the free version without issues but when we bought the pro version, it didn't work out of the box - We've spent hours trying to debug it but there are still errors: 

ERROR  Failed to compile with 1 errors

error  in ./src/main.js

Module build failed: ReferenceError: Unknown plugin "transform-runtime" specified in "~/Desktop/vue-pdp-html-psd-v1.0.0/.babelrc" at 0, attempted to resolve relative to "~/Desktop/vue-pdp-html-psd-v1.0.0"

I read online to run:
npm i babel-plugin-transform-runtime
npm i babel-preset-stage-2
npm i babel-preset-es2015

but it still doesn't work.

I'm using nvm if that matters.

Thanks,
David

**Comment by cristijora** [comment]
Hi @davidchl Very sorry to heart that you had some issues upon installation. So far only 2 people had issues upon installation and the cause was mainly because they used `yarn` together with `npm` which caused some conflicts. You don't have to install any additional packages in order to make it work. It should work fine as it is. I will write down some suggestions and if they don't work, I will need some additional info.

1. Try to delete node_modules folder 
2. Make a fresh install `yarn install` or `npm install` and use only one of them later on for adding packages.
3. It should work with node > 4, but try to use latest stable node version (6.11.3). If you use nvm as stated, then that should be fairly easy `nvm use 6.11.3` if it's already installed or `nvm install 6.11.3` and then `nvm use 6.11.3`

If these things don't work could you please paste here the following files:
`.babelrc`, `package.json` 
You can paste code here using this syntax.
 ``` 
```//code here```
 ```

**Comment by davidchl** [comment]
Thanks for the help on discord Cristi!

For other folks that come here:
Just had to move .babelrc that is in the root folder into /Vuejs.js

and then it all worked
