### ISSUE TITLE
Add '/' to relative paths  for static resources

### ISSUE THREAD

**Issue by Eencsio** [creativetimofficial/vue-paper-dashboard-pro#2]
I just found that when I changed the router mode to history, all the static assets broke because of the redirect routes in src/routes/routes.js file.

To fix it, just add a simple **_'/' (slash)_** before all static asset routes.

Example: 
In file index.html, for the themify-icons

Before:
```
<link href="static/css/themify-icons.css" rel="stylesheet">
```
After:
```
<link href="/static/css/themify-icons.css" rel="stylesheet">
```

[Some reference](https://router.vuejs.org/en/essentials/history-mode.html)

**Comment by cristijora** [comment]
@Eencsio thanks for pointing it out. I removed the slashes because gh-pages where the dashboard is deployed didn't retrieve assets correctly when they had slashes. Have to think about it a bit so we can cover this 'history' mode case as well

**Comment by cristijora** [comment]
If you had any other issues or struggle with something please feel free to post them here. Any feedback is much appreciated as this is our first premium Vue product. Happy coding :) (or less coding with the template 😄 )

**Comment by deivkk** [comment]
The solution proposed by @Eencsio works well when executing "run dev", however some resources cannot be found from a "run dist" installation. I don't know if this is caused after adding the slashes, have you experienced the same problem?

**Comment by cristijora** [comment]
@Eencsio , @deivkk This tip might be useful for you if you use history mode router
Go to `config/index.js` file

and change
`assetsPublicPath: ''` to `assetsPublicPath: '/'` on the build property 

![image](https://user-images.githubusercontent.com/15955045/30343490-74d97ed8-9806-11e7-9b10-8cbc45790518.png)

This should be done only if you use history mode. Otherwise leave it empty.
This change should resolve pretty much all the issues except images which you can add slashes like @Eencsio mentioned

**Comment by deivkk** [comment]
Thanks @cristijora , I have tested it and works fine.

**Comment by cristijora** [comment]
Updated docs regarding [this issue](https://cristijora.github.io/paper-dashboard-pro/documentation.html?selectedKind=General%20tips&selectedStory=Deployment%20tips&full=0&down=1&left=1&panelRight=0&downPanel=storybook%2Factions%2Factions-panel)
