### ISSUE TITLE
v-tab data event when item is selected

### ISSUE THREAD

**Issue by CrzKev** [creativetimofficial/vue-paper-dashboard-pro#34]
```
<vue-tabs @tab-change="callMethod(item)" class="row" direction="vertical" value="Description">
  <div v-for="item in array">
    <v-tab :title="item.name" >
      calculated content on item
    </v-tab>
  </div>
</vue-tabs>
```

what I try to do is trigger a method with the input of the v-tab but the problem is the tab-change is at a higher level any suggestions?

**Comment by cristijora** [comment]
Hello @KH-IT Thanks for using the template and for posting the issue here.
I am not sure I fully understood the question. Let's start off from this [jsfiddle example](https://jsfiddle.net/b44cc4dq/187/) Please edit it with the code you have (general example) and maybe leave some comments where and what method you want to call. Would help a lot! Thanks in advance

**Comment by CrzKev** [comment]
Ok I have updated the example next time I will try to give an example directly!
[jsfiddle example](https://jsfiddle.net/b44cc4dq/689/)

**Comment by cristijora** [comment]
https://jsfiddle.net/b44cc4dq/703/

The `tab-change` event is called with 3 arguments `tabIndex, oldTab, newTab`.
You can use the index to compute the content. The only part to take care is that this should also be done on mounted since `tab-change` will be triggered on change only.

**Comment by CrzKev** [comment]
Thx worked perfectly
